package FlightBookingApp;


/**
* FlightBookingApp/FlightBookingnPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:43:01 PM IST
*/

public abstract class FlightBookingnPOA extends org.omg.PortableServer.Servant
 implements FlightBookingApp.FlightBookingnOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("search", new java.lang.Integer (0));
    _methods.put ("book", new java.lang.Integer (1));
    _methods.put ("cancleBooking", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FlightBookingApp/FlightBookingn/search
       {
         String from = in.read_string ();
         String to = in.read_string ();
         String $result = null;
         $result = this.search (from, to);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FlightBookingApp/FlightBookingn/book
       {
         int id = in.read_long ();
         String name = in.read_string ();
         String date = in.read_string ();
         String $result = null;
         $result = this.book (id, name, date);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FlightBookingApp/FlightBookingn/cancleBooking
       {
         int id = in.read_long ();
         String name = in.read_string ();
         String date = in.read_string ();
         String $result = null;
         $result = this.cancleBooking (id, name, date);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // FlightBookingApp/FlightBookingn/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FlightBookingApp/FlightBookingn:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightBookingn _this() 
  {
    return FlightBookingnHelper.narrow(
    super._this_object());
  }

  public FlightBookingn _this(org.omg.CORBA.ORB orb) 
  {
    return FlightBookingnHelper.narrow(
    super._this_object(orb));
  }


} // class FlightBookingnPOA
