package FlightBookingApp;


/**
* FlightBookingApp/FlightBooking.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:52:12 PM IST
*/

public interface FlightBooking extends FlightBookingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightBooking
