package FlightBookingApp;


/**
* FlightBookingApp/FlightBookingnHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:43:01 PM IST
*/

abstract public class FlightBookingnHelper
{
  private static String  _id = "IDL:FlightBookingApp/FlightBookingn:1.0";

  public static void insert (org.omg.CORBA.Any a, FlightBookingApp.FlightBookingn that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FlightBookingApp.FlightBookingn extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FlightBookingApp.FlightBookingnHelper.id (), "FlightBookingn");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FlightBookingApp.FlightBookingn read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FlightBookingnStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FlightBookingApp.FlightBookingn value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FlightBookingApp.FlightBookingn narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FlightBookingApp.FlightBookingn)
      return (FlightBookingApp.FlightBookingn)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FlightBookingApp._FlightBookingnStub stub = new FlightBookingApp._FlightBookingnStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FlightBookingApp.FlightBookingn unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FlightBookingApp.FlightBookingn)
      return (FlightBookingApp.FlightBookingn)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FlightBookingApp._FlightBookingnStub stub = new FlightBookingApp._FlightBookingnStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
