package FlightBookingApp;

/**
* FlightBookingApp/FlightBookingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:52:12 PM IST
*/

public final class FlightBookingHolder implements org.omg.CORBA.portable.Streamable
{
  public FlightBookingApp.FlightBooking value = null;

  public FlightBookingHolder ()
  {
  }

  public FlightBookingHolder (FlightBookingApp.FlightBooking initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FlightBookingApp.FlightBookingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FlightBookingApp.FlightBookingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FlightBookingApp.FlightBookingHelper.type ();
  }

}
