package FlightBookingApp;

/**
* FlightBookingApp/FlightBookingnHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:43:01 PM IST
*/

public final class FlightBookingnHolder implements org.omg.CORBA.portable.Streamable
{
  public FlightBookingApp.FlightBookingn value = null;

  public FlightBookingnHolder ()
  {
  }

  public FlightBookingnHolder (FlightBookingApp.FlightBookingn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FlightBookingApp.FlightBookingnHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FlightBookingApp.FlightBookingnHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FlightBookingApp.FlightBookingnHelper.type ();
  }

}
