package FlightBookingApp;


/**
* FlightBookingApp/FlightBookingHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:52:12 PM IST
*/

abstract public class FlightBookingHelper
{
  private static String  _id = "IDL:FlightBookingApp/FlightBooking:1.0";

  public static void insert (org.omg.CORBA.Any a, FlightBookingApp.FlightBooking that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FlightBookingApp.FlightBooking extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FlightBookingApp.FlightBookingHelper.id (), "FlightBooking");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FlightBookingApp.FlightBooking read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FlightBookingStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FlightBookingApp.FlightBooking value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FlightBookingApp.FlightBooking narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FlightBookingApp.FlightBooking)
      return (FlightBookingApp.FlightBooking)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FlightBookingApp._FlightBookingStub stub = new FlightBookingApp._FlightBookingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FlightBookingApp.FlightBooking unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FlightBookingApp.FlightBooking)
      return (FlightBookingApp.FlightBooking)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FlightBookingApp._FlightBookingStub stub = new FlightBookingApp._FlightBookingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
