package FlightBookingApp;


/**
* FlightBookingApp/FlightBookingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:52:12 PM IST
*/

public interface FlightBookingOperations 
{
  String search (String from, String to);
  String book (int id, String name, String date);
  String cancleBooking (int id, String name, String date);
  void shutdown ();
} // interface FlightBookingOperations
