package FlightBookingApp;


/**
* FlightBookingApp/FlightBookingn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FlightBooking.idl
* Monday, September 12, 2016 10:43:01 PM IST
*/

public interface FlightBookingn extends FlightBookingnOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlightBookingn
